spring:
  application:
    name: CRM #服务名称
  datasource:
    url: jdbc:mysql://118.25.4.178:3306/spectrum?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    tomcat:
      time-between-eviction-runs-millis: 60000 #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
      min-evictable-idle-time-millis: 300000 #指定一个空闲连接最少空闲多久后可被清除
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
server:
  port: 8103 #运行端口号
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
  httpclient:
    enabled: true
eureka:
  instance:
    lease-expiration-duration-in-seconds: 3 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 2 #服务刷新时间配置，每隔这个时间会主动心跳一次
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://122.51.247.67:8001/eureka/ #配置注册中心地址
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml