spring:
  application:
    name: CRM #服务名称
  datasource:
    url: jdbc:mysql://122.51.247.67:3306/crm?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
server:
  port: 8101 #运行端口号
eureka:
  instance:
    lease-expiration-duration-in-seconds: 3 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 2 #服务刷新时间配置，每隔这个时间会主动心跳一次
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://122.51.247.67:8001/eureka/ #配置注册中心地址